import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/*
  date: 2025.12.29
  title: my projects - portfolio
*/

/**
 * 포트폴리오 사이드바 구성
 *
 * 구조:
 * - intro: 프로젝트 전체 소개
 * - Projects 카테고리: 각 프로젝트별 상세 문서
 *
 * Resume는 navbar를 통해 별도 접근하므로 sidebar에서 제외
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "projects/index",
      label: "🏠 Introduction",
    },
    {
      type: "html",
      value: '<hr style="margin: 1rem 0;" />',
      defaultStyle: true,
    },
    {
      type: "autogenerated",
      dirName: "projects",
    },
  ],
};

export default sidebars;
