import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/*
  date: 2025.12.29
  title: my projects - portfolio
*/

/**
 * 포트폴리오 사이드바 구성
 *
 * 구조:
 * - intro: 프로젝트 전체 소개
 * - Projects 카테고리: 각 프로젝트별 상세 문서
 *
 * Resume는 navbar를 통해 별도 접근하므로 sidebar에서 제외
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "🏠 Overview",
    },
    {
      type: "category",
      label: "📁 Projects",
      collapsed: false, // 기본적으로 펼쳐진 상태
      items: [
        {
          type: "category",
          label: "├─ ReadyBerry └─",
          link: {
            type: "doc",
            id: "projects/readyberry/index",
          },
          items: [
            "projects/readyberry/architecture",
            "projects/readyberry/features",
            "projects/readyberry/tech-stack",
          ],
        },
        // {
        //   type: "category",
        //   label: "BackOffice",
        //   link: {
        //     type: "doc",
        //     id: "projects/backoffice/index",
        //   },
        //   items: [
        //     "projects/backoffice/architecture",
        //     "projects/backoffice/features",
        //   ],
        // },
      ],
    },
  ],

  // tutorialSidebar: [
  //   "intro",
  //   "resume",
  //   {
  //     type: "category",
  //     label: "Projects",
  //     items: ["projects/readyberry"],

  //     // items: ["projects/readyberry", "projects/backoffice"],
  //   },
  // ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
