name: Lint, Test, and Build on Develop

on:
  push:
    branches:
      - develop # develop 브랜치에 푸시될 때 실행

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint # 린트 실행

      - name: Build the project
        run: npm run build # 프로젝트 빌드
